# $FreeBSD: head/include/xlocale/Makefile 266865 2014-05-30 01:09:07Z pfg $ 

NO_OBJ=
INCS=	_ctype.h _inttypes.h _langinfo.h _locale.h _monetary.h _stdio.h\
	_stdlib.h _string.h _strings.h _time.h _uchar.h _wchar.h
INCSDIR=${INCLUDEDIR}/xlocale

.include <bsd.prog.mk>
